INSERT INTO property_photo (pid, imgpath) VALUES
(1, './property_images/propert1/img1.jpg'),
(1, './property_images/propert1/img2.jpg'),
(1, './property_images/propert1/img3.jpg'),
(2, './property_images/propert2/img1.jpg'),
(2, './property_images/propert2/img2.jpg'),
(2, './property_images/propert2/img3.jpg'),
(3, './property_images/propert3/img1.jpg'),
(3, './property_images/propert3/img2.jpg'),
(3, './property_images/propert3/img3.jpg'),
(4, './property_images/propert4/img1.jpeg'),
(4, './property_images/propert4/img2.jpeg'),
(4, './property_images/propert4/img3.jpeg'),
(5, './property_images/propert5/img1.jpg'),
(5, './property_images/propert5/img2.jpg'),
